name: Elixir CI

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: book_my_gigs_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost/book_my_gigs_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.15.7
          otp-version: 26.0

      - name: Install dependencies
        run: mix deps.get

      - name: Format Elixir code
        run: mix format

      - name: Setup database
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run Credo
        run: |
          echo "Running Credo:"
          mix credo

      - name: List test files
        run: |
          echo "Listing test files:"
          ls -l test

      - name: Run tests with ExCoveralls
        run: mix coveralls
